<?php

$plugin = array(
  'title' => t('Site template left bar'),
  'theme' => 'bootstrap_everywhere_site_template_left_bar',
  'icon' => 'bootstrap-everywhere-site-template-left-bar.png',
  'category' => 'Bootstrap everywhere',
  'regions' => array(
    'navbar' => t('Navigation'),
    'header' => t('Header'),
    'hero' => t('Hero unit'),
    'left' => t('Left'),
    'main' => t('Main'),
    'footer' => t('Footer'),
  ),
);
