<?php
/**
 * @file
 * paginas_error.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function paginas_error_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "boxes" && $api == "box") {
    return array("version" => "1");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
