<?php
/**
 * @file
 * auspiciantes_test.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function auspiciantes_test_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Auspicio5',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0eb7fbae-ff35-4cb5-b282-89a4e69bea00',
    'vocabulary_machine_name' => 'auspicios',
    'field_logo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Auspicio3',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '15deb8f2-32dd-486f-b6dd-815bd50572ee',
    'vocabulary_machine_name' => 'auspicios',
    'field_logo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Auspicio2',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9a253424-b26a-4877-8b96-0f2e431203ea',
    'vocabulary_machine_name' => 'auspicios',
    'field_logo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Auspicio4',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9d18943e-2e4c-4a2e-966d-513136647f36',
    'vocabulary_machine_name' => 'auspicios',
    'field_logo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Auspicio1',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ad5a57c5-6a99-4cbc-87c8-70a8e6cce66c',
    'vocabulary_machine_name' => 'auspicios',
    'field_logo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Auspicio6',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f407c5be-2870-4f8a-aaca-0b788e99399c',
    'vocabulary_machine_name' => 'auspicios',
    'field_logo' => array(),
    'metatags' => array(),
  );
  return $terms;
}
