<?php

$plugin = array(
  'title' => t(' Experto Online Site Template 3 columnas'),
  'theme' => 'tutoriame_site_template_3_cols',
  'icon' => 'tutoriame-site-template-3-cols.png',
  'category' => 'Bootstrap everywhere',
  'regions' => array(
    'header' => t('Header'),
    'headerrow' => t('HeaderRow'),
    'left' => t('Left'),
    'main' => t('Main'),
    'right' => t('Right'),
    'footer' => t('Footer'),

  ),
);
