<?php

$plugin = array(
  'title' => t('Site template three columns'),
  'theme' => 'bootstrap_everywhere_site_template_3_cols',
  'icon' => 'bootstrap-everywhere-site-template-3-cols.png',
  'category' => 'Bootstrap everywhere',
  'regions' => array(
    'navbar' => t('Navigation'),
    'header' => t('Header'),
    'hero' => t('Hero unit'),
    'left' => t('Left'),
    'main' => t('Main'),
    'right' => t('Right'),
    'footer' => t('Footer'),
  ),
);
