<?php

function tutoriame_plantillas_permission() {
  return array(
    'administer tutoriame_plantillas settings' => array(
      'title' => t('Administrar plantillas para  Experto Online'),
      'description' => t('Configurar la utilización de plantillas para  Experto Online'),
    ),
  );
}

function tutoriame_plantillas_menu() {
  $items['admin/tutoriame/config/plantillas'] = array(
    'title' => t('Plantillas'),
    'description' => t('Configure las plantillas para mensajería de  Experto Online.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tutoriame_plantillas_admin_settings'),
    'file' => 'tutoriame_plantillas.admin.inc',
    'access arguments' => array('administer tutoriame_plantillas settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

