<?php

/**
 * @file
 * Add Número fields to Location address.
 */

/**
 * Implements hook_locationapi().
 */
function location_calle_numero_locationapi(&$location, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'fields':
      return array('calle_numero' => t('Número'));

    case 'defaults':
      return array(
        'calle_numero' => array('default' => '', 'collect' => 0, 'weight' => 25),
      );

    case 'field_expand':
      if ($a3 == 'calle_numero') {
        return array(
          '#type' => 'textfield',
          '#title' => t('Número'),
          '#size' => 31,
          '#maxlength' => 31,
          '#description' => NULL,
          '#required' => ($a4['collect'] == 2),
          '#default_value' => $location,
        );
      }
      break;

    case 'save':
      db_delete('location_calle_numero')
        ->condition('lid', $location['lid'])
        ->execute();
      if (!empty($location['calle_numero'])) {
        db_insert('location_calle_numero')
          ->fields(array(
            'lid' => $location['lid'],
            'calle_numero' => $location['calle_numero'],
          ))
          ->execute();
      }
      break;

    case 'load':
      $fields = array();
      $calle_numero = db_query('SELECT calle_numero FROM {location_calle_numero} WHERE lid = :lid', array(':lid' => $location['lid']))->fetchField();
      $fields['calle_numero'] = $calle_numero ? $calle_numero : '';
      return $fields;

    case 'delete':
      db_delete('location_calle_numero')
        ->condition('lid', $location['lid'])
        ->execute();
      break;
  }
}

/**
 * Implements hook_views_api().
 */
function location_calle_numero_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_token_list().
 */
function location_calle_numero_token_list($type = 'all') {
  if ($type == 'node' || $type == 'user' || $type == 'all') {
    $tokens['location']['location-calle_numero_N'] = t('Location Número (If there are multiple locations per node, N is the iteration, starting with 0)');
    return $tokens;
  }
}
