<?php
/**
 * @file
 * usuarios.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function usuarios_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Estrategia de Negocios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '006f9617-2580-47c2-af8c-9ddc36f3c57b',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    ),
  );
  $terms[] = array(
    'name' => 'Planeamiento económico-financiero',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '01173ece-56a4-4b0b-8657-8f8efeaeb25e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Aeronavegación',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '01d2dc8b-f238-4341-9979-34fe3092a5de',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'MERCEDES-BENZ COMPAÑIA FINANCIERA ARGENT',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '023d0fca-0ac4-44b4-a63e-ed7ee77eb543',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Control de Gastos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '02835ea2-67ed-467b-b34e-85b27388621e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Medicina Prepaga',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0285bc4d-6b70-446c-a000-64060574d4ec',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sistema de comisiones',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '02a3d1bb-2d29-41cf-abf1-169c64de0e8b',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de San Andrés (UDESA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 41,
    'uuid' => '02a9c6c1-5331-48c4-be06-3ca63cd8cdbd',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Católica Argentina de Rosario',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 26,
    'uuid' => '03c1ca5b-b6a6-40e0-bd49-4754572f5260',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Metalúrgica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '04c670c0-3836-4641-8a00-a874f929f29f',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Mianónides',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 47,
    'uuid' => '04e4a6e8-15f2-410d-8f8b-6cde3c76d25b',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Base de datos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '04f59aa0-9107-4ea6-85ac-a7c34f1efcb8',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'COMPAÑIA FINANCIERA ARGENTINA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0583ac7b-2a54-4ae7-a0fa-1a8b06b98a3a',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Desarrollo Organizacional',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '05aecccc-7363-4277-aa22-fb456dece68b',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    ),
  );
  $terms[] = array(
    'name' => 'Servicios a cliente',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '065bac31-7d32-42d4-8661-a40abab1b81c',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Créditos y Cobranzas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '07dbaa4f-292a-4a31-9e5b-a6a2b0f608be',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Productividad de operarios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '07e8d741-6c55-4603-9c07-6e60114eefea',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'CITIBANK N.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '083db981-58ec-4f87-8f0a-a920ba9c8476',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de San Martín (UNSAM)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 73,
    'uuid' => '08b46bef-4b46-46af-a10d-cde9d8bfea7f',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Programación',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '08db4662-b764-495b-8478-ded672d7fd37',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de Belgrano (UB)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 30,
    'uuid' => '08fe412a-462b-4163-8d42-996f6fb5e7d4',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de San Juan',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 71,
    'uuid' => '0951436f-9715-4917-ad6a-1f7c6de666df',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO SUPERVIELLE S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '09fe0735-47f6-4cc3-baf6-283846723700',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Branding',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0a4909bf-3a41-4664-b13e-1c68972c9e4d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'NUEVO BANCO DE ENTRE RÍOS S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0b3d030b-7d48-43cf-abeb-f138da2ae172',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Argentina de la Empresa (UADE)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 19,
    'uuid' => '0b9567cf-f42a-42a4-98d6-accedcbe7f72',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'IVA no Alcanzado',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0c1919bd-992d-4c8e-90a3-ba3bb103f224',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Asociación sin Fines de Lucro',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0ca2e7ac-7b82-4024-8fcf-10884ea29b9c',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Inmobiliaria',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0cf0b33d-945e-4e59-bf4d-f6e23201b203',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Transportadora',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0d06832c-9f7a-4b2c-ba6f-67b23289496b',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad del norte Santo Tomás Aquino',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 44,
    'uuid' => '0dbb3d37-ca28-48ab-abcd-8037354e993e',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Planeamiento de stocks',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0e0fd193-b7a6-4815-bc02-1350d7dd84f8',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'FORD CREDIT COMPAÑIA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0e69d099-8002-4d2f-948b-ba4dfc8374a8',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Mantenimiento de planta',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0e96918e-2bec-4ce0-aafa-52bf1cd6c77a',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Finanzas Corporativas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0f659460-ae1b-4c40-803f-cd4d8fe35b44',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    ),
  );
  $terms[] = array(
    'name' => 'IVA Sujeto Excento',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0ff114fe-6f1c-401c-8c89-31ab1a2db8b0',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Banca - Financiera',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '10734c14-ff80-4b7f-bd32-0503c1b4e325',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Escribanía',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '11c3c18d-3f31-4cdf-aee6-15e02d2af8ca',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'VOLKSWAGEN CREDIT COMPAÑÍA FINANCIERA S.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '12182eb5-4da8-4aeb-8fec-4d876e4e8348',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Redes sociales',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '128b3853-c69a-4898-9a16-eb3ea339ebbb',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Diseño',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1292b3af-ae45-404f-a9e8-cc7baa221294',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO BRADESCO ARGENTINA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '131e2f5f-5c86-43b7-8f9d-4089152ccb67',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Rosario',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 69,
    'uuid' => '1404eeb4-3c63-47e0-87fe-92ba9bc376dd',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Católica Argentina de Mendoza',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 25,
    'uuid' => '14248943-267b-421b-8b29-624901790087',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Data Entry',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '143e8151-842c-4a04-b11a-9f4897a5844c',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => 'Redacción',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '14b8b901-0425-443c-af02-85c94459ffd4',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Arquitectura',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '15bbb8b3-b8f5-4c40-9367-9104eff5ab65',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ac726d5d-e639-4934-8886-1a7cf924f65c',
    ),
  );
  $terms[] = array(
    'name' => 'Diseño',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '15c0bfca-1f6e-4f83-95cc-a333abb6f83a',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Metalmecánica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '16168db7-11b3-4e86-b382-a39f1c644ce0',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Periodismo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '164f82c4-a2b8-4203-9311-461ec20fba2f',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de Flores (UFLO)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 35,
    'uuid' => '17a3123b-56d3-4fab-b921-612d58f40268',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Gestión de proyectos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '180910f1-5fc0-4be0-be8a-78dd41c01a77',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Escuela de Dirección y Negocios de la Universidad Austral (IAE)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '18ad72d6-4ced-40ab-ba57-7951f412bfe8',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Colegio Universitario IES Siglo 21',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '18ef8b2a-8472-4b33-b8fe-4c330113f09b',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Electromecánica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '193a78a3-d19a-43b2-817f-09b9d9f1916b',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'AMERICAN EXPRESS BANK LTD. SOCIEDAD ANON',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '19f5d542-6097-4ff9-afb3-79fa6de17748',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Dirección de Obra',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1a6ce268-7599-4578-952f-30c6552fbe05',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ac726d5d-e639-4934-8886-1a7cf924f65c',
    ),
  );
  $terms[] = array(
    'name' => 'Relaciones Laborales',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1ae39b80-cc05-48bd-b1c3-3ea2c244c296',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'Administración general',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1bc6e6d1-48f8-409c-909e-c9cdfe83d34e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Auditoría',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1bf8b4ee-4627-408d-bae2-67c41211aebf',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Marketing Online / Digital',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1c7b8e22-e2a8-4f96-9693-d99d00654d8b',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Gobierno',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1d76d665-63b2-4c7a-a457-0244e51ff89a',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Instituto Universitario Aeronáutico (IUA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 13,
    'uuid' => '1dd7c11f-c833-448a-9a1e-a28046c6a247',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Administración de Base de Datos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1e496b01-e3ba-4391-9cfa-8cd1d405c3bf',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO CMF S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1e4fbd34-20fd-450f-bba1-e0613fbfd32b',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Cédula de Identidad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '200aa162-f892-45e8-967d-34d272aca66f',
    'vocabulary_machine_name' => 'tipo_de_documento',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '+ 5000',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '206b94e6-beae-44a2-9b9e-42db4c068685',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO CETELEM ARGENTINA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '20f35957-9076-412f-bee4-1a8528804398',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería de Producto',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2189763a-06ca-485b-9b00-7b60ade70d9b',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Congresos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '21cefaae-4ad3-4064-842b-b7c13f6dfb7a',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Hotelería',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '22eecfe7-2878-4a88-b5ce-0a6cff81ef81',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Business Intelligence',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '23947286-9715-4438-b283-9dd69861c459',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Holding',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '23986b12-7b32-453b-a5ae-468c2cd150a0',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Artíatica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '27e412aa-7bd7-42bc-99a9-a3e84d11b214',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Contabilidad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '28e6dade-7bc2-495c-b768-4f2ae98155f2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Telecomunicaciones',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '292ee3d2-3241-4907-a067-aeb00817f1e0',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Católica Argentina de Salta',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 27,
    'uuid' => '298079cd-11c7-4980-b7b3-1aabaf777ff6',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DO BRASIL S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '299fcb78-f1d8-4dcd-be5d-827ad9dd4842',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE SAN JUAN S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2a2af2c8-915a-4b26-a396-ed4408df7b85',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Supermercado - Hipermercado',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2a46a965-8e25-487a-a33d-721b534c6064',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Portugués',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2a4c3613-5cfd-44bb-b10b-69df8f537245',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Servicios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2c18f208-0603-432b-aba0-9ff60a5af9b8',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO HIPOTECARIO S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2c4925a3-d92e-4d2a-8fe6-d8a269008210',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE LA CIUDAD DE BUENOS AIRES',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2c7784a0-2204-4603-8546-891b03dd5518',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de la Patagonia San Juan Bosco',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 59,
    'uuid' => '2ca48c20-3edf-4836-ae92-561159592cc9',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Comercio Exterior',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2d5a1cc6-076d-419f-8f1c-e472ca956ac7',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Inglés',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2d5f3551-1860-4c64-b8cb-5f578626a585',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Recursos Humanos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Contenidos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2dfef375-b631-4ae6-82a8-d4fe6f42a3d4',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Programación de producción',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2e3f8401-4443-4f21-9b41-a682801aad49',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Comercio',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2f2b1622-e162-42b0-b79d-fae37c51fa42',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Back Office',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '30b39879-7000-4882-919b-f7132adce13f',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => 'DNI',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '30b3b13d-68d2-4b6b-80e0-d55b02333236',
    'vocabulary_machine_name' => 'tipo_de_documento',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Reingenería de procesos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '30c06798-226b-4410-824d-b5725a3bcf5e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'Artículos en diarios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '30d929bb-814f-4c1e-8abd-8fa65d6f00e1',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE FORMOSA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3147220c-9ce3-4cf2-9667-3b70c4405da5',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad FASTA - Mar del Plata',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 46,
    'uuid' => '3175596e-f05f-452e-ab13-11fcae4265ef',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'FINANDINO COMPAÑÍA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '31757b6c-7797-49ea-8de1-46282ed1deba',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Almacenamiento / Logística / Distribución',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Almacén',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '35187bb7-4e32-4bc6-a4a2-e45c0b4cbc71',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'Fuerza de ventas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3541d136-2871-40fa-90d3-c750d5f5a452',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Ventas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '35ddf083-5f0b-4b46-b8bb-4f6891cd1ffc',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Defensa',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '35ed78ec-14e1-4d5d-988a-bb13e4ddee11',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Catamarca',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 48,
    'uuid' => '3604f907-d1dd-4c1d-996c-4d70a6a27b5a',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Córdoba',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 50,
    'uuid' => '360c1029-e4e2-4b37-937d-3485d18537b5',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'NUEVO BANCO DE LA RIOJA SOCIEDAD ANONIMA',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '36703bc0-3f9c-460c-8052-aff229106871',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'JOHN DEERE CREDIT COMPAÑÍA FINANCIERA S.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '37442a22-ba84-4ede-b3e5-01da1e2fe363',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Medios y Comunicación',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '395e3890-e7b1-48b3-a52d-440522428b0d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Evaluación Económica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3962cacf-93a3-4fc1-ba0a-f4b0799fc749',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO DE LA NACION ARGENTINA',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '39d13c5a-e557-428d-829e-678dca3097a8',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Soporte Técnico / Mesa de Ayuda',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3a41d5e5-923d-4afe-a3cf-bbff4b9adb59',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Administración de Personal',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3a8f154f-846b-406f-a7de-b4902e37bbde',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'Diseño Multimedia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3aa75c4a-3787-422b-af52-249e1d9fdfa9',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '1292b3af-ae45-404f-a9e8-cc7baa221294',
    ),
  );
  $terms[] = array(
    'name' => 'Instituto Argentino de Secretarias Ejecutivas (IASE)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '3b49cf3d-ae7b-4bae-a68b-d9e52ea96aca',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Organizaciones No Gubernamentales',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3b4a6719-29f5-4a1d-bc0c-abfb5ea59362',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Cuyo',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 51,
    'uuid' => '3c65fc39-5cb1-4c21-a8ab-bf71d67a150f',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Deportes',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3d8ea3ea-5d8f-441f-9784-4d9e6a84989f',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Consumidor Final',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3dd699a1-9a04-4893-af25-d019f97479f4',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Cosmética',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3e13e86d-8866-46f1-8cc4-f8b7bcd177d6',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Data Warehousing',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3e7b4530-d1ea-44f4-bfa7-16fbc8223bd2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Maderera',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3f0e18f3-977e-425d-b542-ec50b4b31938',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Neumático / Caucho',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3f3ab9bd-403d-4ceb-b3f4-c158d95075d7',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Compras',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '40d9fab4-a77b-4eea-a302-736d8c9aeb66',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'abb0b686-eba3-40a3-b07c-833b23c6884a',
    ),
  );
  $terms[] = array(
    'name' => 'Publicidad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '41263950-3001-4f8f-8421-64151a6d0160',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Alimentos y Bebidas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '42b6ae27-691f-42b4-8e00-b2a237d577bd',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Servicios Petroleros',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '42f9f559-f485-449f-b9a0-e4d694e2a89a',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Expedición',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4424b6a6-5a2a-4775-adaf-a49ebfd549df',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'ART',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '44cdbaa8-461c-4bd1-8401-b636088d4741',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Retail',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '452c0289-4d0c-47c4-9c8d-09d3ab6ad649',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Proyectos de inversión',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '46e2a367-655a-4a5e-87bf-4d5c97968662',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional del Nordeste',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 80,
    'uuid' => '47ec154d-37a0-4fa8-aada-ec71aec63f35',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'LC',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '4818bd2d-b8d2-4434-b90e-73f26e170b73',
    'vocabulary_machine_name' => 'tipo_de_documento',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Finanzas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '490303d0-fae8-4dc9-9bc4-c4eca1225388',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Administración de Ventas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '49593f64-3559-4301-8310-5618c96b8af2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Pequeño Contribuyente Eventual Social',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '49a2b624-e6d9-48a6-bca2-62a45efe0585',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Textil',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '49fa9788-70a9-47b3-a6a8-6afe47c83566',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE LA PAMPA SOCIEDAD DE ECONOMÍA M',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4a308ccd-1b5b-4f85-ba5c-95baad73fd10',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Desarrollo de Negocios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4bb922e5-385d-4c62-ade2-82e0c4564853',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de Buenos Aires (UBA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 31,
    'uuid' => '4bc13d24-b68c-45d4-9ce4-790c3a5fa5f5',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Desarrollo Comercial',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4cf80b31-e4e5-4b60-a9a6-a183b1ecd152',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Recursos Humanos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4d34d832-f383-4d9e-aac9-0e905cc169e2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO DE LA REPUBLICA ORIENTAL DEL URUGU',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4d4d6eaa-782d-4f61-bfeb-0a54cc4645dc',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Mecánica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4e024a43-84e4-4d83-b69c-19167ba39b43',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Servicios Públicos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4eac9447-2dd9-4ede-b3d0-dad4d10700f0',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Investigación de Mercado',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4eb98f83-e390-4952-9708-2136290ef448',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'MONTEMAR COMPAÑIA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4f720396-38de-4b67-a58a-fe4a3ad4df27',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tutor',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '50508538-f697-4d5e-b7a6-27bdc1b2b2e2',
    'vocabulary_machine_name' => 'rol_en_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE LA PROVINCIA DE BUENOS AIRES',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '50d31175-3798-430a-bac5-9305242a779c',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Austral',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 21,
    'uuid' => '51a904d6-beae-41d6-a012-3d9ea4a88cde',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Medios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '51b7fa7f-0d4b-4b81-be36-a5189672e42b',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '101 a 500',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '52ac3705-37f4-4448-b874-fb21a17556e2',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Industrial',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '53f68c32-4008-4aec-b29e-1af12c23efb1',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Control de Calidad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '54580b0b-ce7e-46b4-9e4f-c3991bcb14a7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Comunicaciones internas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '55273b8c-2df5-42b9-b5d8-c819d4740ce2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'Artesanal',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5665434e-5032-45ce-83fa-3470816965d2',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'THE ROYAL BANK OF SCOTLAND N.V.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '56fd7d4a-ab70-41d4-8a84-de823c771d8e',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Productos para la cosntrucción',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '575779b5-b15a-490b-9992-4a12c30a83a8',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO JULIO SOCIEDAD ANONIMA',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '575a1898-2046-4874-aeae-48ddc69a258e',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Testing / QA / QC',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '579a9123-e82a-474f-ad0c-6bd1802e9518',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Pesca',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '58e61ca9-29c2-4ae7-bcb3-406626d168ff',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Tucumán',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 76,
    'uuid' => '5901ac5e-e352-4c15-90e9-2e455803c0bb',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Electrónica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '592e0e91-f072-40ee-a105-65b4d83e9a1a',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Seguridad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '59abdd17-db26-4aca-b6a4-cc47340bdb4a',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Gestión de proyectos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5a13ed05-0f13-4007-a4e3-a0e18de917b8',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    ),
  );
  $terms[] = array(
    'name' => 'Otros',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Organización de Eventos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5a66f9ac-8e0d-41f9-b8b2-7dacf311e24e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'a06c500d-a44c-473a-9d2a-b70181833d5e',
    ),
  );
  $terms[] = array(
    'name' => 'Soporte administrativo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5b2777a5-7a75-4d19-917c-a3df5217c7c7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO DE LA PROVINCIA DE CORDOBA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5b2d3743-4338-48d0-b9bc-465e6125ba31',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad de Cema (UCEMA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 32,
    'uuid' => '5b9b6046-4909-46d5-b34b-3cb01a9bfc88',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Distribución',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5c33f6ac-d55a-4144-b079-bb42d865c797',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'Programas de fidelización',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5c9e2790-2436-4854-b936-9da759afcaa2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Tablero de Control',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5e45231f-033a-4342-b1c5-6c2bbf9417d7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Impuestos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5ead4e71-4b91-4954-a908-7c41436094ca',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Naviera',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5f4120e7-5e07-4df9-a4b0-223363e8b9d8',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Depósito',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '60f70656-2de2-495a-8e28-642de2f6fbb3',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de Morón (UM)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 38,
    'uuid' => '612e10c7-afc8-462a-a66a-ee14145d77d2',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Proveedor de exterior',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '61aa1099-0345-4c6b-a494-815014712975',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Presupuesto y control de gestión',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '61c53873-a354-4da3-9ff0-9f76dabd2c90',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Operaciones',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '61cc395b-eca4-4b56-915d-0fe773d9d0c3',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Diseño de planos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '62024db3-b04a-4556-bbd6-705d005d89e6',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ac726d5d-e639-4934-8886-1a7cf924f65c',
    ),
  );
  $terms[] = array(
    'name' => 'Educación',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '630652a4-c538-4ccf-b4ab-d465811aac5d',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '1 a 20',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '6316706f-9f1a-44fb-884b-54b6a364257e',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Instituto Universitario Nacional de Arte (IUNA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 14,
    'uuid' => '631feb9f-fb1d-49da-b7be-00bab6a02299',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Higiene y Perfiumería',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '64c700dc-fe49-4931-8b87-6629279b37df',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Otro',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => '64fdd0f2-15a5-4c72-b0a8-86d52b2e426e',
    'vocabulary_machine_name' => 'tipo_de_documento',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sistemas / Tecnología / IT',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Centro de Altos Estudios de Ciencias Exactas (CAECE)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '65fd7260-4631-41ed-8da0-745024cd1158',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Análisis de Riesgos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '68594209-8137-4180-bc1c-599b17089991',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Tres de Febrero',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 75,
    'uuid' => '687666a3-0c98-42c7-b420-c96d2e6e8a14',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'DEUTSCHE BANK S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '687d2afe-ef45-4321-b667-431cd96f381b',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE SERVICIOS FINANCIEROS S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '689d1f39-9db7-4f93-bb2e-fec390e61b33',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Investigación y Desarrollo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '68eac790-0a5b-4ede-a876-9fc96a49c6d6',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'GPAT COMPAÑIA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '69bfa09e-ee3b-4aaf-8018-047ef784f58b',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Management general',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Agroindustria',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6c1ff19e-a001-4239-a650-9396d18baa5d',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería de Procesos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6d47efb5-369d-460c-ae69-d1f25a4ad527',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Análisis Funcional / Liderazgo de Proyecto',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6d6f7c8f-a9a8-4e08-a657-85613775d792',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Villa María',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 77,
    'uuid' => '6d7ecdc6-70d9-4d59-8231-a4c65ebea877',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO FINANSUR S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6e682bd5-85ea-41ab-9466-a3e024aea36c',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Automotriz',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6f4f7fe7-429a-42d1-a3c7-731000450034',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DEL SOL S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6f5d1b9e-593c-4c49-a9b7-d3156df160e6',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO ROELA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '70ad7650-cef6-4961-ba61-23f1090eb1e4',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Diseño Industrial',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '71668b57-a449-4500-9e26-e857c1ad1f1d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '1292b3af-ae45-404f-a9e8-cc7baa221294',
    ),
  );
  $terms[] = array(
    'name' => 'Publicidad en radio',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => '729189dd-4acd-4056-aa8c-6f212a7d9296',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tecnología / Infraestructura',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7466c79a-9acf-4146-ab8d-35b652391307',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Diseño Gráfico',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '750b2193-c572-44e4-8a6d-48f295f8a9ee',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '1292b3af-ae45-404f-a9e8-cc7baa221294',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de Ciencias Empresariales y Sociales (UCES)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 33,
    'uuid' => '754d064a-3da0-4158-9241-2c9c5490c02a',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Electrónica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '75595931-833c-49ed-baff-dac1ce358494',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Biotecnología',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '75683d7c-e6d8-4e42-915e-bd66e90cb4f1',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO PIANO S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7671e015-5e6a-411b-a326-7bed48297ecc',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'ROMBO COMPAÑÍA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '76d4283a-91eb-44ed-952d-a1f88042cbb7',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Transporte - Logística - Distribución',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '78cc1351-a834-41c5-b70d-728caf090286',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE SANTIAGO DEL ESTERO S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '795cf64b-6f0e-48d5-8f2a-dd3f3b9e5798',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Presencia en Universidades',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '7992ef47-57d2-4f0e-a8ab-27514465717e',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Abierta Interamericana (UAI)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 17,
    'uuid' => '79b720c2-6d8f-47a4-ad0d-3f4d2a743020',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de la Patagonia Austral',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 58,
    'uuid' => '79cfc0fe-ac43-4374-90cf-40367855f922',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'RCI BANQUE S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7a2ac536-77b4-4df5-8a3a-130577aa5ac3',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'E-Commerce',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7a8b2c60-379b-4a88-81d4-9fa18572fe41',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Torcuato Di Tella (UTDT)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 83,
    'uuid' => '7b4ff3cc-0423-47cc-8ee5-4920fccdaa8e',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Mantenimiento y Limpieza',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7bf65a0b-3f62-4004-94d6-ae4316a31ebb',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO COINAG S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7c2357b4-a55e-4842-9a00-79d83bc1616d',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Astillero',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7ca415f9-0d3d-4cca-8827-d25dca405b34',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Calidad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7cc22941-8fbb-49f6-9381-0999dcda1658',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Productividad fuerza de ventas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7d06606c-7db9-4148-9fc0-82ee0d4d80b8',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Coaching',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7d2415ed-060b-4425-9430-0f118d8b5697',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Emprearial Siglo 21',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 45,
    'uuid' => '7dea0795-417a-41c5-852c-526ec3e73fc4',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '51 a 100',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '7e0a8047-77f8-4634-adfe-daad63ddc5d7',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Cliente de Exterior',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7eaddd38-946d-4b81-b8bf-f681196de37c',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Diseño Textil e Indumentaria',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7eaf84b2-e56d-4635-b581-ca9e6e700e61',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '1292b3af-ae45-404f-a9e8-cc7baa221294',
    ),
  );
  $terms[] = array(
    'name' => 'Información e Investigación',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7ee9ed95-4d4e-4de7-9f37-9afd82fbde2f',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Publicidad en TV',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '7ef7eb16-971b-4748-ad9c-571081eeb42f',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad de Salvador (USAL)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 40,
    'uuid' => '7f65c757-5f71-4ec0-9976-5e15c6952465',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Entretenimiento',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7fa22bc4-9cc6-4c03-a0fa-0c7658963950',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'IVA Responsable Inscripto',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8103b22c-2462-4823-9813-66cd45bd90c7',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'CORDIAL COMPAÑIA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '81bbd534-fda0-4231-974f-1790c954219c',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Imprenta',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '81f86a20-3588-4445-a2d2-f6493d80054d',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Seguridad Informática',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8272ed55-7de8-474e-9ab1-99c3aaba46e9',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de Congreso',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 34,
    'uuid' => '8275a9cc-61c1-41c8-a954-a4c5658d98b8',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional del Sur',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 81,
    'uuid' => '8356a01e-4cd1-4cfb-b42f-204a1aad4600',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Desarrollo de Negocios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '83fbbc7c-6991-4708-8b99-d885b7b80c61',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    ),
  );
  $terms[] = array(
    'name' => 'Comercio Exterior',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '844f8d62-d88a-4f94-b77a-7777cb401681',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'abb0b686-eba3-40a3-b07c-833b23c6884a',
    ),
  );
  $terms[] = array(
    'name' => 'Otros',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '852cac4e-921d-4a0f-8a34-48570c6bcf61',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Santiago del Estero',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 74,
    'uuid' => '85b97ba4-00c8-4e73-9b86-be23493d6be8',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Luján',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 64,
    'uuid' => '86264b54-2887-48ed-b4d7-7901870dfdd5',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'METROPOLIS COMPAÑIA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '86468310-c379-4c61-80b5-e03bea5f09ba',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Química',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '865be893-4f82-42d6-842b-dcab02be2a98',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Administración y Finanzas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO SANTANDER RIO S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '86b3ad9e-bd3a-46c8-a01f-efb779db7fe2',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO PATAGONIA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8703f442-79be-4b01-9547-c849693fe3d7',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Quilmes',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 67,
    'uuid' => '872ace4b-dbb9-487d-9ca8-185e91564afa',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BBVA BANCO FRANCES S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '87903a03-304f-4ae4-8998-abbdbcdd6d27',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Papelera',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8916f0e7-4c9e-487b-8017-ae424a4cf729',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'CAJA DE CREDITO "CUENCA" COOPERATIVA LIM',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8a377e1e-ac2f-4e4a-82e3-b775894e32f2',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Plásticos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8bbedd10-ba9c-4bef-a171-aaf890bb43b2',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería de Ventas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8bc87dc6-c249-4f6b-b9b0-4c506114efaf',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'AFJP',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8d5804ce-efbe-43ce-ad29-ede3a22d6a42',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Marketing',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8da6b4ec-ec74-4f3a-ae96-e579cbaa9f17',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO MUNICIPAL DE ROSARIO',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8e037620-db49-4f7f-91a1-3813f992829c',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Manejo de Microsoft Excel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8eb23e4d-eabe-4f8c-8bcc-40c7454bc0b7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Derecho Societario',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8effa69e-7a6d-41cd-af27-9d67cf40c2d2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'UMS',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 16,
    'uuid' => '8f066609-a852-499d-91c8-20e5052be4a5',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'LE',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '8f3f314b-9c28-4372-b96e-14fb88238fa7',
    'vocabulary_machine_name' => 'tipo_de_documento',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Recomendación de un conocido',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => '8f697a71-ff1f-4db9-b78e-963d18c5c102',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'HSBC BANK ARGENTINA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '917a1417-b8cd-4908-853e-16260e84f74f',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Pasaporte',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '91881b03-9917-4ccb-b729-efca0872d8db',
    'vocabulary_machine_name' => 'tipo_de_documento',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Instituto para el Desarrollo Empresarial de la Argentina (IDEA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '919f044c-3d58-48a2-b3e3-4b3807886b48',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO CREDICOOP COOPERATIVO LIMITADO',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '91aaf5d8-9d14-49c8-8533-501f86859c12',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Aduana',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9225505a-74a0-4f67-8aaa-135ae6172342',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'abb0b686-eba3-40a3-b07c-833b23c6884a',
    ),
  );
  $terms[] = array(
    'name' => 'Poder Judicial',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9378b4b4-8a45-4f47-9020-ba66724795d6',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería y Producción',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Diseño Web',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '93ecaa76-28d0-4ec1-9231-81e9e490d2b5',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '1292b3af-ae45-404f-a9e8-cc7baa221294',
    ),
  );
  $terms[] = array(
    'name' => 'Agricultura y Ganadería',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '941fe264-6233-4f92-97a4-40b346f139de',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Otros',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => '950c7fdc-df7d-41ce-add0-8a40ba0b88d6',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Industria',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '95df35e1-6357-428c-b917-49270aabc80e',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'NUEVO BANCO DE SANTA FE SOCIEDAD ANONIMA',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '99213b8f-16f3-467d-9504-7fa4455113fa',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Publicidad / Marketing / RRPP',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9973a58f-979d-4029-9ba7-249ce9ed15ef',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Marcas y Patentes',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '99fac89c-6946-4282-9508-433fd78e8330',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'Turismo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9a97bd38-8212-473b-b062-abfc3583e849',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Planeamiento estratégico',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9af8e296-2d30-4285-8955-07dfff907596',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    ),
  );
  $terms[] = array(
    'name' => 'Instituto San Pio X',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 10,
    'uuid' => '9b6336b5-e828-4cf1-bbd5-ad3996ce0045',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Fundación de Altos Estudios en Ciencias Comerciales',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '9b884548-e2e7-4d7f-8852-0f01730234c5',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Argentina de Cuyo',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 18,
    'uuid' => '9c01ece6-0b3e-4bac-adf3-5d1460d7ea94',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sistemas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9cecc94f-39de-424d-bd24-cd9049a999cd',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de La Plata',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 60,
    'uuid' => '9dfff777-62f7-4353-9e20-3d7f4a2e689a',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tecnología',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9e0d8ae9-c87b-44b0-9c09-b7046495abdb',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Fusiones y adquisiones/ M&A',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9e81b930-0a66-4c0f-bab1-14aa0c5a6ee8',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de La Rioja',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 61,
    'uuid' => '9eb92b27-e6a3-402c-a7bc-373e89ec7654',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Consitución de empresas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9edfd7e9-0e46-47fa-bb17-c73796c91591',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'Inversiones',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9eec0997-9e97-43ea-8b68-7b2f3d7bc52e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Despachante de Aduana',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9f41185c-38d1-4e16-a809-1030939b4f9d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'abb0b686-eba3-40a3-b07c-833b23c6884a',
    ),
  );
  $terms[] = array(
    'name' => 'Publicidad Gráfica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '9f8803d0-9d3c-448f-aa0f-9cc41e95cd4b',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Caja de ahorro en Pesos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a00da974-460e-4c88-bf43-8733f8d0d7ec',
    'vocabulary_machine_name' => 'tipo_de_cuenta',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad de Mendoza',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 37,
    'uuid' => 'a012fb0d-55f6-44ca-8e21-35fe733042aa',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Fondos de Inversión',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a0540313-a5b6-40f6-8352-1fd5cf19a24f',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Relaciones Institucionales / Públicas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a06c500d-a44c-473a-9d2a-b70181833d5e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Relaciones Públcias',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a1967afd-977b-4e03-9af3-30479bbc44be',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'a06c500d-a44c-473a-9d2a-b70181833d5e',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO DE SERVICIOS Y TRANSACCIONES S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a1bee728-fe80-4fe7-b932-9d1f5dfe3b49',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Química',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a2a778a2-d46b-40e1-8038-a51cdc28dab3',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Correo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a33f434d-8840-48f5-abd2-3fa09d0b1d98',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'MULTIFINANZAS COMPAÑIA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a36a42f6-e6e4-4c52-bfb2-c93d351eed33',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Cuenta corriente en Pesos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a4b7c02c-b3a4-4fba-8246-f6bada0d1d61',
    'vocabulary_machine_name' => 'tipo_de_cuenta',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Español',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a65f4c44-9b27-4226-be73-b40ac7a94cab',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Producto',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a6bfe960-2e0b-4c06-8f5b-07b9d628a93d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Católica Argentina (UCA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 23,
    'uuid' => 'a7e60444-f1d7-4f15-9536-07124a27d730',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad de Palermo (UP)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 39,
    'uuid' => 'a7ed43c6-7573-425e-9c8b-f55601f31f97',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Eléctrica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a871c340-9e1a-4449-a5c0-e80e0752566a',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad de Marina Mercante',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 36,
    'uuid' => 'a90982f2-6ece-47c2-8247-285f723579cb',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Planes de incentivos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a9c830cd-d10a-476a-825f-a10d56d4353e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO PRIVADO DE INVERSIONES SOCIEDAD AN',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aa1a9cc7-18a9-47ed-a7ca-c4a58133d0e6',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Entre Ríos',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 52,
    'uuid' => 'aa99c999-7885-4098-8b63-8b66585958f9',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Electrodomésticos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aba53d59-ddab-4497-a0b2-1d50003e4904',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'IVA Responsable Inscripto - Agente de Percepción',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'abaf14ac-f86b-4217-87bf-2bfbbc1989a9',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Compras y Abastecimiento',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'abb0b686-eba3-40a3-b07c-833b23c6884a',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Contabilidad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'abf476e3-fa7e-4826-a5df-14c63913b49c',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Arquitectura',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ac726d5d-e639-4934-8886-1a7cf924f65c',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad de Aconcagua (UDA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 29,
    'uuid' => 'ad50c853-b0f0-4206-a79a-e7548427492c',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad del Museo Social Argentino (UMSA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 43,
    'uuid' => 'ad573c13-97cb-4a79-8f70-7105ad47a038',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Editorial',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ad8e0652-f37e-45f0-be53-e9b763fd6ad3',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE SANTA CRUZ S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b02c843a-d784-426b-919d-051ff623e321',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Comahue',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 49,
    'uuid' => 'b0a17add-7031-45e6-aa9e-2ca1d40977e5',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO BICA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b0af94f4-3d96-47ff-be9c-beb5ccea16d7',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO MASVENTAS S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b12bc80d-56d7-413d-b9d1-c7dbf937e661',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Jujuy',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 55,
    'uuid' => 'b163f372-577e-4487-b017-63347b02f3bf',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE CORRIENTES S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b1c9b665-7950-44ad-8633-7202ba04d860',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Legales',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Derecho Ambiental',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b27abf1a-be51-4328-90bc-6f535ae7e516',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'Producción Audiovisual',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b2833d1d-652c-46e4-8497-a69d02bd7fcf',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Análisis de estados contables',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b39f465f-cfdc-424f-be8d-057db98a2c3f',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Consumo Masivo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b4381307-3e32-4082-aca2-cdacc7997385',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Logística',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b5a02eea-dcae-40e2-96d1-6ad26be022e2',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO ITAU ARGENTINA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b5f0675d-be5c-4d08-adc6-d374216931dc',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BNP PARIBAS',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b65dc298-84b8-4b83-bdfc-fe3450696866',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional del Litoral',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 79,
    'uuid' => 'b68d08de-5292-4cd3-8890-882622c0f259',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería en Telecomunicaciones',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b6eada13-ab21-4d08-bbea-890d09a6d8dd',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Discografía',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b80cce37-c36e-4f0a-bdc4-d9f0610f98ae',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Oficina Técnica / Proyecto',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b86b0d9c-3283-4fec-b156-44ebd2f1ae3f',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Publicidad en Internet',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'b97e7190-958d-4ee1-8ad8-7b4f39c84b44',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b991e272-8d43-4abf-b423-1649cbc6d898',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Pequeño Contribuyente Eventual',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b993c8ac-5528-406c-b829-6605b2cf2544',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Instituto Tecnológico de Buenos Aires (ITBA)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 12,
    'uuid' => 'b9c835f6-30b7-4804-ab63-9ace12db210a',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO SAENZ S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bad9ae2a-ac09-4671-9afa-dfbc69f77062',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Laboratorio',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bb13146f-e379-459d-bcdc-61f4ab0b984d',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '21 a 50',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => 'bb9a2d6d-13a6-4d19-9527-94a33b05b228',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Blas Pascal',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 22,
    'uuid' => 'bc2d2804-10e3-4c39-bde8-09a0f5b97067',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ente regulador',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bcd47590-6ad9-4e1c-8a72-48d7a630962d',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tabacalera',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bd423778-0b23-4117-a1bd-4de701a04667',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Redes',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bd80752d-3813-4d8c-b9a8-dc1b6390b990',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '652ece00-1b04-4e28-b82a-ef168f9e7e7d',
    ),
  );
  $terms[] = array(
    'name' => 'TOYOTA COMPAÑÍA FINANCIERA DE ARGENTINA',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bde1fbb6-45a4-41fa-9fde-1b001ea316b2',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO INTERFINANZAS S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'be064aea-de18-4af4-b61f-8dc24810e3d9',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Civil',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bf0d4088-38bd-4127-a9e0-6c3382693de7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Abastecimiento',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bf5f0cce-e2c1-49c8-bf20-de384f0e9278',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'abb0b686-eba3-40a3-b07c-833b23c6884a',
    ),
  );
  $terms[] = array(
    'name' => 'Análisis de negocios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bf8d72d2-8629-4f68-b46d-d793aeccb9d1',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c0050aed-38bb-433e-b9a8-2819e4dcac13',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE INVERSION Y COMERCIO EXTERIOR S',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c041c767-327c-4369-9f41-2a03ed40c675',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '2001 a 5000',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => 'c04851d4-f09b-4a93-b5e1-f1d8cc4a5638',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Petroquímica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c0979e9b-2cea-4567-a4eb-2d95882fdb93',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO COMAFI SOCIEDAD ANONIMA',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c0dcae5f-6a8e-49c7-ad74-cf185597f8bb',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Formosa',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 53,
    'uuid' => 'c1013a23-69ae-4016-be44-ebcbea055cc5',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Seguros',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c129f4d3-14d2-45e6-9724-6106ce66bb52',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Producción',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c2927343-3bfd-4e00-8e28-e16a8ca4dda7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'ISO',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c2a7cb50-3d8d-472e-a5ac-c1b7b6f85314',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Católica de Córdoba',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 28,
    'uuid' => 'c3d314e6-db1a-466e-8e4b-70d73233a437',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Constitución',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c3db7c81-6ae0-4b76-aefa-29f208866aea',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Siderurgia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c488a2cc-f2e9-4af4-a307-787735ce5118',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Derecho del Consumidor',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c531e279-818a-49c3-9696-bfe84e7fbded',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'Frigorífico',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c56abfa5-39bf-41dc-b01d-6abc4ecd3ed9',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'IVA Liberado - Ley Nro 19.640',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c5d98aa0-07a3-419b-9d1d-2807582a832e',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Cerealera',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c6703aa6-45b7-401a-bdaf-e0b971cc6ce3',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Trabajo Social',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c7f2e14b-6cab-48a2-b75c-0bd0778c9504',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => 'PSA FINANCE ARGENTINA COMPAÑÍA FINANCIER',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c844605f-dd3a-4fe8-8582-62f04d6f635f',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Salud',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c84a19ae-36f3-4a77-b0c1-f1ae63a25aed',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANK OF AMERICA, NATIONAL ASSOCIATION',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c84b1c4d-0e3a-4d0b-811e-5982de106829',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Planeamiento comercial',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c8a92b96-69ee-4dc9-97fa-9e3795d3325e',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Escuela Argentina de Negocios',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => 'c8b59e74-8d06-4bdf-ab8a-1ec9caba6686',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tesorería',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c8e188fb-1445-4b93-909a-ac964635e22d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Capacitación y Desarrollo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c8f7350a-44a2-40d1-b3d6-70baf9295141',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'Planes de negocios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c90ad6c9-cc6c-46a1-afb1-283a4002f48f',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Organización Internacional',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cb6bcfc5-bc66-4283-95b7-b7588e91364e',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Facturación',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cbcae414-7791-472d-a685-feb023bd48a5',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Mar del Plata',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 65,
    'uuid' => 'cd87d5e4-c2fe-4c06-92dd-7f8750d20364',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Farmacéutica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ced5c39c-1e28-4a47-a232-5fac714a1118',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Argentina John F.Kennedy',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 20,
    'uuid' => 'cf5bf8a4-bc5f-48bf-8eb0-1575de4feea6',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO MERIDIAN S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd11b5b70-c5a0-4c1f-90d8-3556efc9ab32',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Salta',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 70,
    'uuid' => 'd1a6cb1d-367e-4a43-b6ed-68f2b186c308',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Gestión de inventarios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd2fceadc-d1ad-45e5-a7fe-39b88486a09d',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '33d33766-79a5-4cdd-b4bf-a68cb46f07a7',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de San Luis',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 72,
    'uuid' => 'd37bd3a1-b5e9-48b6-98be-6b014363eecf',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Río Cuarto',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 68,
    'uuid' => 'd3e90986-c7f8-4fc8-ad3d-aa0d8f8ff465',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO PROVINCIA DE TIERRA DEL FUEGO',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd3ff66d8-bf90-4d27-9dc3-2e46850bfc8a',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Católica Argentina de La Plata',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 24,
    'uuid' => 'd4895cdc-4548-4812-af26-a8b7c15be2c4',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Telemarketing',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd83d7491-5fb1-4a17-a29b-3603754cfa19',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    ),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de La Pampa',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 57,
    'uuid' => 'd96e43f3-8581-4e11-9287-b0d24fcd85de',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Relaciones Institucionales',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'da940ed4-3a2a-4b36-8a22-74171253b972',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'a06c500d-a44c-473a-9d2a-b70181833d5e',
    ),
  );
  $terms[] = array(
    'name' => 'Seguros',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dab122ec-3c2c-4f06-a6f5-f2b4828a6464',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Gráfica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'db69fb55-8732-4809-bd6a-09e6874155dc',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Arquitectura',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dcb98a3e-6ae1-40e9-9276-58b470bf8832',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Instituto Superior Octubre',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 11,
    'uuid' => 'dcc87053-d04f-40a5-aa66-f1c33ed9651f',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'FIAT CREDITO COMPAÑIA FINANCIERA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dd1c81c7-0bdd-4687-9115-bc270101d239',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Seguridad Industrial / Higiene / Medio Ambiente',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dd4d4262-b87f-4609-9b85-fe0c18720ef0',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Asociación Argentina de Agencias de Publicidad (AAAP)',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ddcf4f65-9f52-476a-b771-b69153d9b92b',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Derecho Laboral',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ddee2e32-b94d-4664-b6c6-769ed67a2bb5',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'THE BANK OF TOKYO-MITSUBISHI UFJ, LTD.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ddf15c44-02f9-4bc2-94f0-2c8207968113',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Caja',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ddfe9936-bdbc-4516-880a-9ad839cc96cb',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => '501 a 1000',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'de6dd367-72c2-452d-bf18-bde807064d94',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Monotributista Social',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'df770430-296c-443d-bcad-8400e5855fb1',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad del Centro Educativo Latinoamericano (UCEL)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 42,
    'uuid' => 'df99483a-744b-4fa7-b8e5-2cfba932af80',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Seguridad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dfb94279-14c3-49da-af20-63cb3e3a2f46',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => 'Curtiembre',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e04536e5-4942-405b-82e8-3825725eb9e0',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE VALORES S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e05ce42e-0cd8-4819-8e7c-7127c3a25419',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'NUEVO BANCO DEL CHACO S. A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e0a8a07c-15c6-4d21-a594-6e2a5c73e256',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DEL TUCUMAN S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e13b237f-84af-45f1-a6ae-c8cf10eca4e4',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO DE GALICIA Y BUENOS AIRES S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e1e1f81d-2b32-4bd3-be83-bdea7b443b40',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Tecnológica Nacional (UTN)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 82,
    'uuid' => 'e3fed7c6-5cb7-46d9-9115-d4e46ab8cdd4',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Mueblería',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e4042ebe-0f56-46b0-9314-9b35a6dd42e6',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Promotoras/es',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e81bf746-bd1f-4dee-b11e-b7639b068683',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '5a598add-59f0-44cd-afd7-b200de5d9d7c',
    ),
  );
  $terms[] = array(
    'name' => 'Ecología',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e9a8f1ce-92aa-48a1-b479-c94c29148677',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Escuela Superior de Hotelería (ESH)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'e9eb870f-0f04-4591-bc17-8b6a77be2138',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO COLUMBIA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e9f5dfeb-100d-401b-b8f1-2fe55967e738',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sin Empleados',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ea9aed96-267d-4a95-be5a-6c59831bcc5e',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'General discussion',
    'description' => '',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ec23f5af-47b5-41f4-b959-4fb8ec25dc4c',
    'vocabulary_machine_name' => 'forums',
    'field_institucion' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Forestal',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ed1b0f31-1575-4eb0-9fdb-0f2b4e37d439',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Agrónoma',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ed5147fa-7eab-4bc4-9016-6672b8cd321c',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'BACS BANCO DE CREDITO Y SECURITIZACION S',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ed5c0376-7141-4db0-b3fb-39fe0057dc8e',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Otra',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 84,
    'uuid' => 'ed75b4f4-f42b-4a15-b586-45fe10d248fe',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Facultad Latinoamericana de Ciencias Sociales (FLACSO)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'ed97ea89-768b-46b9-8f08-b75e339ea467',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '1001 a 2000',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'ee8957f1-046c-45e3-9661-f989ed4e5ea3',
    'vocabulary_machine_name' => 'dotaci_n_de_la_empresa',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Manufactura',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'eee93c23-3159-496e-9924-da5b2b001a7e',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Marketing y Ventas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ef04b32b-095e-44ac-8e58-c1584b4887c7',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Fusiones y adquisiones/ M&A',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f02d75fd-537b-4272-b82d-5ebcdd5a0183',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'Pinturas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f03a9f1e-3cd7-4e68-ae5b-a67028545952',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Productividad y eficiencia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f089d412-ae24-426a-bc56-38dde34a8d08',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '6a6e20ae-7b9e-4fff-a10d-ce5099ec7cdb',
    ),
  );
  $terms[] = array(
    'name' => 'Remuneraciones / Compen. y Beneficios',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f0b0fd53-03cc-4f17-9a58-32ac9e744214',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO MARIVA S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f0b675f3-6067-43a3-a972-9f573aa208fd',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Emprendedor',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f0c175d8-6619-4ac5-931b-1cae6fcb093d',
    'vocabulary_machine_name' => 'rol_en_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería Ambiental',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f13493d5-f614-433e-8243-6980cf3b05ed',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'BANCO DEL CHUBUT S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f181d89b-9aec-4962-a618-c2b36a8f6119',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Gastronomía',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f2ac8faf-a7f3-41cf-919c-a3858667a07f',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Traducción',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f399d879-bd55-4473-9b42-19d8fd2732dd',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '395e3890-e7b1-48b3-a52d-440522428b0d',
    ),
  );
  $terms[] = array(
    'name' => 'Research',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f3cf7e09-7a22-47f8-98e1-c134e7018ca8',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '86b39b8c-6524-410d-acdf-2ed0c135b4ec',
    ),
  );
  $terms[] = array(
    'name' => 'Selección y Empleos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f44af95c-f8e2-40b3-9fc5-7d40544f51d4',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '2d672b89-e3ff-4f10-aca6-936217d4e93d',
    ),
  );
  $terms[] = array(
    'name' => 'Derecho Tributario',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f49139c7-15c3-4756-ba9e-dd810cb40db9',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'b26af94f-0eb3-4fbe-9573-f1294fbec0b3',
    ),
  );
  $terms[] = array(
    'name' => 'Por un evento',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => 'f4c7722f-82f8-4682-b457-3b65af8d3103',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Responsable Monotributo',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f5f327f4-286e-4df7-8990-77ba54e8271f',
    'vocabulary_machine_name' => 'responsabilidad_ante_el_iva',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ingeniería en Alimentos',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f5fb971d-6321-40ec-b956-bfe1a486114c',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '93b0562c-7add-4745-bbd4-e3b55811f1eb',
    ),
  );
  $terms[] = array(
    'name' => 'Por buscador de Internet',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => 'f732ce5f-6ff4-4a9b-8b8a-36fd264a1f30',
    'vocabulary_machine_name' => 'medio_conoci_tutoriame',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Bienes de Capital',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f78b16b9-2148-41b2-b7e0-4d25e1f00ff7',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Lanús',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 62,
    'uuid' => 'f83e27ec-fad1-47ff-a0cd-48d421c2aa80',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'ORT',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 15,
    'uuid' => 'f8f77761-6630-44fd-a85b-5be9c8d046b3',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO PROVINCIA DEL NEUQUÉN SOCIEDAD ANÓ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f908f56a-4b47-45f6-81a9-5fa082402084',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Misiones',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 66,
    'uuid' => 'f962d150-4aa1-4916-a2db-59da8b2a982c',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Minería / Petróleo / Gas',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f97c9abd-9ce9-43bf-bf62-7fe66b2169e8',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Autocad',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f9e5a9e7-8b52-44b1-8cae-d103fd9a2ea0',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => 'ac726d5d-e639-4934-8886-1a7cf924f65c',
    ),
  );
  $terms[] = array(
    'name' => 'Jurídica',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fa6f416f-d4ef-4058-9744-c168c9a000a5',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional del Centro de la Provincia de Buenos Aires',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 78,
    'uuid' => 'fb6dcdf9-4971-468a-aa24-085d043fdc8e',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de General Sarmiento',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 54,
    'uuid' => 'fbc23ca2-bc5e-44ec-a5ef-eeec76772864',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Diseño de Interiores / Decoración',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fbca1f17-cf4e-4a07-b6cf-49cfa86c7d11',
    'vocabulary_machine_name' => 'tutorias_categorias',
    'metatags' => array(),
    'parent' => array(
      0 => '1292b3af-ae45-404f-a9e8-cc7baa221294',
    ),
  );
  $terms[] = array(
    'name' => 'Consultoría / Auditoría',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fbfc0a6b-006c-45f3-bdc8-07fd890f6df2',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de Lomas de Zamora',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 63,
    'uuid' => 'fc5ac9ac-282b-4fb4-a739-d32e3a50cafe',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Energía',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fc64c026-dbbf-4777-ac1a-2b57396268cf',
    'vocabulary_machine_name' => 'ramo_o_actividad',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'MBA LAZARD BANCO DE INVERSIONES S. A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fe506125-f7bd-4351-9f17-5feb3f14bd67',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO MACRO S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'feb2d0d6-2785-49b3-a8fb-76eecf08ccd4',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BANCO INDUSTRIAL S.A.',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ff52c2ab-d28f-45b1-9648-08d3d6361cbf',
    'vocabulary_machine_name' => 'banco',
    'field_codigo' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Universidad Nacional de la Matanza',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 56,
    'uuid' => 'ffcf025b-eda3-4829-8165-9a5b397cbc71',
    'vocabulary_machine_name' => 'formacion_institucion',
    'metatags' => array(),
  );
  return $terms;
}
