<?php

/**
 * @file
 * Add depto fields to Location address.
 */

/**
 * Implements hook_locationapi().
 */
function location_depto_locationapi(&$location, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'fields':
      return array('depto' => t('Depto / Oficina'));

    case 'defaults':
      return array(
        'depto' => array('default' => '', 'collect' => 0, 'weight' => 25),
      );

    case 'field_expand':
      if ($a3 == 'depto') {
        return array(
          '#type' => 'textfield',
          '#title' => t('depto'),
          '#size' => 31,
          '#maxlength' => 31,
          '#description' => NULL,
          '#required' => ($a4['collect'] == 2),
          '#default_value' => $location,
        );
      }
      break;

    case 'save':
      db_delete('location_depto')
        ->condition('lid', $location['lid'])
        ->execute();
      if (!empty($location['depto'])) {
        db_insert('location_depto')
          ->fields(array(
            'lid' => $location['lid'],
            'depto' => $location['depto'],
          ))
          ->execute();
      }
      break;

    case 'load':
      $fields = array();
      $depto = db_query('SELECT depto FROM {location_depto} WHERE lid = :lid', array(':lid' => $location['lid']))->fetchField();
      $fields['depto'] = $depto ? $depto : '';
      return $fields;

    case 'delete':
      db_delete('location_depto')
        ->condition('lid', $location['lid'])
        ->execute();
      break;
  }
}

/**
 * Implements hook_views_api().
 */
function location_depto_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_token_list().
 */
function location_depto_token_list($type = 'all') {
  if ($type == 'node' || $type == 'user' || $type == 'all') {
    $tokens['location']['location-depto_N'] = t('Location depto (If there are multiple locations per node, N is the iteration, starting with 0)');
    return $tokens;
  }
}
