<?php

/**
 * @file
 * Add Calle fields to Location address.
 */

/**
 * Implements hook_locationapi().
 */
function location_calle_locationapi(&$location, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'fields':
      return array('calle' => t('Calle'));

    case 'defaults':
      return array(
        'calle' => array('default' => '', 'collect' => 0, 'weight' => 25),
      );

    case 'field_expand':
      if ($a3 == 'calle') {
        return array(
          '#type' => 'textfield',
          '#title' => t('Calle'),
          '#size' => 31,
          '#maxlength' => 31,
          '#description' => NULL,
          '#required' => ($a4['collect'] == 2),
          '#default_value' => $location,
        );
      }
      break;

    case 'save':
      db_delete('location_calle')
        ->condition('lid', $location['lid'])
        ->execute();
      if (!empty($location['calle'])) {
        db_insert('location_calle')
          ->fields(array(
            'lid' => $location['lid'],
            'calle' => $location['calle'],
          ))
          ->execute();
      }
      break;

    case 'load':
      $fields = array();
      $calle = db_query('SELECT calle FROM {location_calle} WHERE lid = :lid', array(':lid' => $location['lid']))->fetchField();
      $fields['calle'] = $calle ? $calle : '';
      return $fields;

    case 'delete':
      db_delete('location_calle')
        ->condition('lid', $location['lid'])
        ->execute();
      break;
  }
}

/**
 * Implements hook_views_api().
 */
function location_calle_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_token_list().
 */
function location_calle_token_list($type = 'all') {
  if ($type == 'node' || $type == 'user' || $type == 'all') {
    $tokens['location']['location-calle_N'] = t('Location Calle (If there are multiple locations per node, N is the iteration, starting with 0)');
    return $tokens;
  }
}
